image: registry.gitlab.com/bred1810/docker-herdtools

build-tools:
    script:
        - make all D=ocb
    only:
        - merge_requests
        - master

test:
    script:
        - make test D=ocb
    only:
        - merge_requests
        - master
