image: registry.gitlab.com/bred1810/docker-herdtools

stages:
    - build
    - test

build-tools:
    stage: build
    script:
        - make all
    only:
        - merge_requests
        - master

test:
    stage: test
    script:
        - make test
    needs: ["build-tools"]
    only:
        - merge_requests
        - master
